from fastapi import FastAPI, HTTPException
from sqlalchemy import text
import httpx
from database import SessionLocal, Users, Crops
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

# Define who is allowed to talk to your API
origins = [
    "http://localhost",
    "http://localhost:3000", # Common for React
    "http://localhost:5173", # Common for Vite/Vue/React
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "https://squaremaxtech.com",
    # Add your production domain here later
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # For a hackathon, "*" allows EVERYTHING. 
    allow_credentials=True,
    allow_methods=["*"], # Allows GET, POST, OPTIONS, etc.
    allow_headers=["*"], # Allows all headers
)

def generate_farming_alerts(stats: dict):
    alerts = []
    
    # 1. Disease Risk (Fungal/Blight)
    if stats['humidity'] > 80 and stats['temperature'] > 20:
        alerts.append({
            "type": "DISEASE_RISK",
            "level": "HIGH",
            "message": "High humidity and warmth detected. Monitor for fungal growth or blight."
        })

    # 2. Operations (Chemical Spraying)
    if stats['wind_speed'] > 15:
        alerts.append({
            "type": "OPERATIONAL_DANGER",
            "level": "CRITICAL",
            "message": "Wind speeds too high for pesticide/fertilizer spraying. Risk of drift."
        })
    elif stats['wind_speed'] < 5:
        alerts.append({
            "type": "OPERATIONAL_INFO",
            "level": "IDEAL",
            "message": "Perfect wind conditions for precise spraying."
        })

    # 3. Resource Management (Watering)
    if stats['precipitation'] > 0:
        alerts.append({
            "type": "RESOURCE_SAVING",
            "level": "INFO",
            "message": "Rain detected. Suspend irrigation to save water and prevent root rot."
        })

    # 4. Planting Safety (Soil Temp)
    if stats['soil_temp'] < 10:
        alerts.append({
            "type": "PLANTING_WARNING",
            "level": "WARNING",
            "message": "Soil is cold. Heat-loving seeds (maize/peppers) may not germinate."
        })

    return alerts

CROP_FACTS = {
    "tomato": {"min_temp": 10, "max_temp": 35, "opt_low": 21, "opt_high": 24, "water": "high"},
    "maize": {"min_temp": 10, "max_temp": 35, "opt_low": 25, "opt_high": 30, "water": "medium"},
    "lettuce": {"min_temp": 7, "max_temp": 24, "opt_low": 15, "opt_high": 18, "water": "high"}
}

def analyze_crop_suitability(current_temp, current_humidity):
    report = {}
    
    for crop, facts in CROP_FACTS.items():
        # Check if current temp is in the 'Danger Zone'
        if current_temp < facts["min_temp"] or current_temp > facts["max_temp"]:
            status = "CRITICAL: Extreme conditions for this crop."
        # Check if current temp is in the 'Sweet Spot'
        elif facts["opt_low"] <= current_temp <= facts["opt_high"]:
            status = "OPTIMAL: Perfect growing conditions."
        else:
            status = "STRESSED: Sub-optimal growth likely."
            
        report[crop] = status
        
    return report

def check_disease_risk(temp, humidity):
    risk_level = "Low"
    potential_disease = "None"
    
    # Famous "Smith Period" logic for Blight
    if humidity > 90 and 15 < temp < 25:
        risk_level = "High"
        potential_disease = "Late Blight / Fungal Outbreak"
    elif humidity > 80 and temp > 28:
        risk_level = "Medium"
        potential_disease = "Root Rot / Bacterial Wilt"
        
    return {"risk": risk_level, "target": potential_disease}

@app.get("/", tags=["health"])
async def read_root() -> dict:
    return {"message": "FastAPI starter is running"}


@app.get("/db-test", tags=["db"])
def db_test() -> dict:
    """Simple endpoint that checks the database connection."""
    with SessionLocal() as db:
        result = db.execute(text("SELECT 1")).scalar_one()
    return {"db_ok": result == 1, "value": result}

@app.get("/users")
def get_users():
    """Reads all rows from the users table."""
    with SessionLocal() as db:
        # 1. Query the reflected class
        all_users = db.query(Users).all()
        
        # 2. Convert SQLAlchemy objects to a list of dicts for JSON response
        # Using .__dict__ is the 'hackathon speed' way to serialize
        return [
            {column: getattr(user, column) for column in user.__table__.columns.keys()} 
            for user in all_users
        ]

@app.post("/users/add")
def create_user(username: str, email: str):
    """Writes a new row to the users table."""
    with SessionLocal() as db:
        # 1. Create a new instance of the reflected class
        new_user = Users(username=username, email=email)
        
        # 2. Add and Commit
        db.add(new_user)
        db.commit()
        db.refresh(new_user) # Get the new ID generated by Postgres
        
        return {"status": "success", "user_id": new_user.id}

@app.get("/weather", tags=["external"])
async def get_weather(lat: float, lon: float):
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": lat,
        "longitude": lon,
        "current": "temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,soil_temperature_0cm",
        "timezone": "auto"
    }
    
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, params=params)
            response.raise_for_status()
            data = response.json()
            current = data.get("current")
            units = data.get("current_units")

            return {
                "location": {"lat": lat, "lon": lon},
                "stats": {
                    "temperature": current.get("temperature_2m"),
                    "humidity": current.get("relative_humidity_2m"),
                    "precipitation": current.get("precipitation"),
                    "wind_speed": current.get("wind_speed_10m"),
                    "soil_temp": current.get("soil_temperature_0cm")
                },
                "units": {
                    "temp": units.get("temperature_2m"),
                    "humidity": units.get("relative_humidity_2m"),
                    "precipitation": units.get("precipitation")
                }
            }
        except httpx.HTTPError as e:
            raise HTTPException(status_code=500, detail=f"Weather service error: {str(e)}")

@app.get("/weather-save")
async def get_and_save_weather(lat: float, lon: float):
    # 1. Fetch from API
    weather_info = await get_weather(lat, lon)
    
    # 2. Save to Postgres
    with SessionLocal() as db:
        new_log = WeatherLogs(
            latitude=lat, 
            longitude=lon, 
            temp=weather_info["temperature"]
        )
        db.add(new_log)
        db.commit()
        
    return weather_info

def generate_farming_alerts(stats: dict):
    alerts = []
    
    # 1. Disease Risk (Fungal/Blight)
    if stats['humidity'] > 80 and stats['temperature'] > 20:
        alerts.append({
            "type": "DISEASE_RISK",
            "level": "HIGH",
            "message": "High humidity and warmth detected. Monitor for fungal growth or blight."
        })

    # 2. Operations (Chemical Spraying)
    if stats['wind_speed'] > 15:
        alerts.append({
            "type": "OPERATIONAL_DANGER",
            "level": "CRITICAL",
            "message": "Wind speeds too high for pesticide/fertilizer spraying. Risk of drift."
        })
    elif stats['wind_speed'] < 5:
        alerts.append({
            "type": "OPERATIONAL_INFO",
            "level": "IDEAL",
            "message": "Perfect wind conditions for precise spraying."
        })

    # 3. Resource Management (Watering)
    if stats['precipitation'] > 0:
        alerts.append({
            "type": "RESOURCE_SAVING",
            "level": "INFO",
            "message": "Rain detected. Suspend irrigation to save water and prevent root rot."
        })

    # 4. Planting Safety (Soil Temp)
    if stats['soil_temp'] < 10:
        alerts.append({
            "type": "PLANTING_WARNING",
            "level": "WARNING",
            "message": "Soil is cold. Heat-loving seeds (maize/peppers) may not germinate."
        })

    return alerts

@app.get("/farmer-dashboard", tags=["Logic"])
async def get_dashboard(lat: float, lon: float):
    # 1. Get raw weather (using your existing function)
    weather_data = await get_weather(lat, lon)
    
    # 2. Extract stats for our logic function
    stats = weather_data["stats"]
    
    # 3. Generate the alerts
    active_alerts = generate_farming_alerts(stats)
    
    return {
        "location": weather_data["location"],
        "current_conditions": stats,
        "alerts": active_alerts,
        "alert_count": len(active_alerts)
    }

@app.get("/crs-analysis")
async def get_crs_analysis(lat: float, lon: float):
    weather = await get_weather(lat, lon) # Your Open-Meteo function
    stats = weather["stats"]
    
    suitability = analyze_crop_suitability(stats['temperature'], stats['humidity'])
    disease_risk = check_disease_risk(stats['temperature'], stats['humidity'])
    
    return {
        "current_weather": stats,
        "crop_suitability": suitability,
        "disease_outlook": disease_risk,
        "advice": "Irrigation recommended" if stats['precipitation'] == 0 else "Rain detected"
    }

@app.get("/recommendations", tags=["CRS Engine"])
async def get_recommendations(lat: float, lon: float):
    # 1. Fetch live weather
    weather_response = await get_weather(lat, lon)
    current_temp = weather_response["stats"]["temperature"]
    
    with SessionLocal() as db:
        # 2. Filter crops based on the DB your admin populated
        # Automap handles the fact that 'id' is a UUID automatically
        viable_crops = db.query(Crops).filter(
            Crops.minTemp <= current_temp,
            Crops.maxTemp >= current_temp
        ).all()
        
        recommendations = []
        for crop in viable_crops:
            is_optimal = crop.optLow <= current_temp <= crop.optHigh
            
            recommendations.append({
                "id": str(crop.id), # Explicitly cast UUID to string for JSON safety
                "crop_name": crop.name,
                "suitability": "OPTIMAL" if is_optimal else "VIABLE",
                "advice": f"Ideal range: {crop.optLow}°C - {crop.optHigh}°C",
                "humidity_target": f"{crop.idealHumidity}%"
            })
            
        result = {
            "metadata": {
                "lat": lat,
                "lon": lon,
                "current_temp": f"{current_temp}°C",
                "weather_condition": "Fetched via Open-Meteo"
            },
            "count": len(recommendations),
            "suggestions": recommendations
        }

        if not recommendations:
            result["message"] = "No suitable crops found for this climate."
            
        return result
